package initfile_test

import (
	"strings"
	"testing"
	"time"

	"github.com/JtheGunner/omnishell/internal/initfile"
)

func sections() []initfile.Section {
	return []initfile.Section{
		{ID: "completion", Version: "1.0.0", Body: "autoload -Uz compinit && compinit\n"},
		{ID: "fzf", Version: "1.2.0", Body: "source fzf.zsh\n"},
		{ID: "empty", Version: "1.0.0", Body: ""},
	}
}

func TestBuildStructure(t *testing.T) {
	ts := time.Date(2026, 9, 2, 22, 41, 3, 0, time.UTC)
	got := initfile.Build("zsh", sections(), ts)

	if !strings.Contains(got, "GENERATED BY omnishell") {
		t.Fatal("missing generated header")
	}
	if !strings.Contains(got, "# >>> omnishell:completion (v1.0.0) >>>") ||
		!strings.Contains(got, "# <<< omnishell:completion <<<") {
		t.Fatalf("missing completion markers:\n%s", got)
	}
	if strings.Contains(got, "omnishell:empty") {
		t.Fatal("empty section should be skipped")
	}
	if !strings.Contains(got, "Content hash: "+initfile.ContentHash(sections())) {
		t.Fatal("header hash mismatch")
	}
	if strings.Index(got, "omnishell:completion") > strings.Index(got, "omnishell:fzf") {
		t.Fatal("section order not preserved")
	}
}

func TestDetectHandEdit(t *testing.T) {
	ts := time.Date(2026, 9, 2, 22, 41, 3, 0, time.UTC)
	content := initfile.Build("zsh", sections(), ts)

	edited, err := initfile.DetectHandEdit(content, sections())
	if err != nil {
		t.Fatal(err)
	}
	if edited {
		t.Fatal("freshly built file reported as hand-edited")
	}

	tampered := strings.Replace(content, "autoload -Uz compinit && compinit", "rm -rf /", 1)
	edited, _ = initfile.DetectHandEdit(tampered, sections())
	if !edited {
		t.Fatal("tampered file not detected")
	}

	edited, _ = initfile.DetectHandEdit("no header here", sections())
	if !edited {
		t.Fatal("headerless content should count as edited")
	}
}

func TestMatchesGeneratedForm(t *testing.T) {
	ts := time.Date(2026, 9, 2, 22, 41, 3, 0, time.UTC)
	content := initfile.Build("zsh", sections(), ts)

	if !initfile.MatchesGeneratedForm("zsh", content) {
		t.Fatal("pristine Build output should match its generated form")
	}

	if initfile.MatchesGeneratedForm("zsh", content+"\n# tampered\n") {
		t.Fatal("trailing edit outside markers should not match")
	}

	headerEdit := strings.Replace(content, "Content hash: ", "Content hash: sha256:0000", 1)
	if initfile.MatchesGeneratedForm("zsh", headerEdit) {
		t.Fatal("altered header line should not match")
	}

	if initfile.MatchesGeneratedForm("zsh", "no header here") {
		t.Fatal("content without a header should not match")
	}
}

func TestContentHashOrderSensitive(t *testing.T) {
	s := sections()
	swapped := []initfile.Section{s[1], s[0], s[2]}
	if initfile.ContentHash(s) == initfile.ContentHash(swapped) {
		t.Fatal("hash should depend on section order")
	}
}

func TestDetectHandEditIgnoresSectionsParameter(t *testing.T) {
	// Verify that DetectHandEdit returns false when file content matches
	// the header, regardless of what sections parameter is passed.
	// This ensures the function is pure tamper detection on file content.

	ts := time.Date(2026, 9, 2, 22, 41, 3, 0, time.UTC)
	content := initfile.Build("zsh", sections(), ts)

	// File was built from sections(), so it should not be edited
	edited, err := initfile.DetectHandEdit(content, sections())
	if err != nil {
		t.Fatal(err)
	}
	if edited {
		t.Fatal("freshly built file reported as hand-edited")
	}

	// Now pass different sections. File still matches its header, so should
	// not be reported as edited.
	differentSections := []initfile.Section{
		{ID: "totally", Version: "2.0.0", Body: "different sections\n"},
		{ID: "from", Version: "1.0.0", Body: "the file\n"},
	}
	edited, err = initfile.DetectHandEdit(content, differentSections)
	if err != nil {
		t.Fatal(err)
	}
	if edited {
		t.Fatal("sections parameter should not drive the result; file matches its own header")
	}
}

func TestDetectHandEditZeroSectionsGolibFallback(t *testing.T) {
	// Verify fallback behavior: if content has a valid header hash but
	// no parseable section markers, use the sections parameter to decide.

	// Create content with a valid header hash but no section markers
	headerOnlyContent := `# ─────────────────────────────────────────────────────────────
#  GENERATED BY omnishell — DO NOT EDIT
#  Source of truth: ~/.config/omnishell/config.toml
#  Regenerate: omnishell apply
#  Shell: zsh
#  Generated: 2026-09-02T22:41:03Z
#  Content hash: sha256:abc123def456
# ─────────────────────────────────────────────────────────────
`

	// When passed expected sections, should report edited=true because
	// the hash doesn't match what sections would produce
	edited, err := initfile.DetectHandEdit(headerOnlyContent, sections())
	if err != nil {
		t.Fatal(err)
	}
	if !edited {
		t.Fatal("file with no sections but content hash mismatch should be reported as edited")
	}

	// With empty sections, should also report edited (different hash)
	edited, err = initfile.DetectHandEdit(headerOnlyContent, []initfile.Section{})
	if err != nil {
		t.Fatal(err)
	}
	if !edited {
		t.Fatal("file with no sections should report as edited when hash doesn't match fallback")
	}
}
