// Package initfile assembles the tool-managed shell init file, hashes its
// module sections, and detects manual edits.
package initfile

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"time"
)

// Section is one module's rendered contribution to an init file.
type Section struct {
	ID      string
	Version string
	Body    string
}

// blank reports whether the section's Body is empty or only whitespace.
func (s Section) blank() bool {
	return strings.TrimSpace(s.Body) == ""
}

// ContentHash is an order-sensitive hash of the module sections only.
// It skips empty sections (matching what Build outputs).
func ContentHash(sections []Section) string {
	var b strings.Builder
	for _, s := range sections {
		// Skip empty sections, matching Build behavior
		if s.blank() {
			continue
		}
		b.WriteString(">>>")
		b.WriteString(s.ID)
		b.WriteByte(0)
		b.WriteString(s.Version)
		b.WriteByte(0)
		b.WriteString(s.Body)
		b.WriteString("<<<\n")
	}
	sum := sha256.Sum256([]byte(b.String()))
	return "sha256:" + hex.EncodeToString(sum[:])
}

const headerSentinel = "GENERATED BY omnishell"

// Build returns the full init file content for a shell.
func Build(shell string, sections []Section, generatedAt time.Time) string {
	var b strings.Builder
	_, _ = fmt.Fprintf(&b, "# ─────────────────────────────────────────────────────────────\n")
	_, _ = fmt.Fprintf(&b, "#  %s — DO NOT EDIT\n", headerSentinel)
	_, _ = fmt.Fprintf(&b, "#  Source of truth: ~/.config/omnishell/config.toml\n")
	_, _ = fmt.Fprintf(&b, "#  Regenerate: omnishell apply\n")
	_, _ = fmt.Fprintf(&b, "#  Shell: %s\n", shell)
	_, _ = fmt.Fprintf(&b, "#  Generated: %s\n", generatedAt.UTC().Format(time.RFC3339))
	_, _ = fmt.Fprintf(&b, "#  Content hash: %s\n", ContentHash(sections))
	_, _ = fmt.Fprintf(&b, "# ─────────────────────────────────────────────────────────────\n")

	for _, s := range sections {
		if s.blank() {
			continue
		}
		body := s.Body
		if !strings.HasSuffix(body, "\n") {
			body += "\n"
		}
		_, _ = fmt.Fprintf(&b, "\n# >>> omnishell:%s (v%s) >>>\n", s.ID, s.Version)
		b.WriteString(body)
		_, _ = fmt.Fprintf(&b, "# <<< omnishell:%s <<<\n", s.ID)
	}
	return b.String()
}

// ParseHeaderHash extracts the "Content hash:" value from the header.
func ParseHeaderHash(content string) (string, bool) {
	for _, line := range strings.Split(content, "\n") {
		if i := strings.Index(line, "Content hash:"); i >= 0 {
			return strings.TrimSpace(line[i+len("Content hash:"):]), true
		}
		if !strings.HasPrefix(strings.TrimSpace(line), "#") && strings.TrimSpace(line) != "" {
			break // past the header
		}
	}
	return "", false
}

// parseGeneratedAt reads the "Generated:" RFC3339 stamp from the header.
func parseGeneratedAt(content string) (time.Time, bool) {
	for _, line := range strings.Split(content, "\n") {
		i := strings.Index(line, "Generated:")
		if i < 0 {
			continue
		}
		ts := strings.TrimSpace(line[i+len("Generated:"):])
		t, err := time.Parse(time.RFC3339, ts)
		return t, err == nil
	}
	return time.Time{}, false
}

// MatchesGeneratedForm reports whether content is byte-for-byte what Build would
// produce for the sections currently written in it: a parseable header with a
// Content hash line, a parseable "Generated:" timestamp, and a body that is
// exactly Build(shell, <sections parsed from content>, <that timestamp>).
// It detects trailing/header/inter-section tampering that DetectHandEdit (which
// only hashes in-marker section bodies) cannot.
func MatchesGeneratedForm(shell, content string) bool {
	if _, ok := ParseHeaderHash(content); !ok {
		return false
	}
	gen, ok := parseGeneratedAt(content)
	if !ok {
		return false
	}
	return Build(shell, extractSectionsFromContent(content), gen) == content
}

// DetectHandEdit reports whether content has been hand-edited.
// Returns true iff:
// (a) content has no parseable Content hash: header line, OR
// (b) the SHA-256 recomputed from the section bodies actually present in content
//
//	differs from that header hash.
func DetectHandEdit(content string, sections []Section) (bool, error) {
	headerHash, ok := ParseHeaderHash(content)
	if !ok {
		return true, nil
	}
	// Extract sections from file and check if file has been hand-edited
	extracted := extractSectionsFromContent(content)

	// If no sections were parsed (header exists but no markers), fall back to
	// the caller's expected sections so a truncated/gutted file still counts as edited
	if len(extracted) == 0 {
		return headerHash != ContentHash(sections), nil
	}

	// File has parseable sections; compare their hash to the header hash.
	// Pure tamper detection: only cares about what's in the file, not the parameter.
	return headerHash != ContentHash(extracted), nil
}

// extractSectionsFromContent extracts Section objects from file content.
func extractSectionsFromContent(content string) []Section {
	var result []Section
	lines := strings.Split(content, "\n")

	var current *Section
	var bodyLines []string

	for _, line := range lines {
		// Check for section start marker
		if strings.HasPrefix(line, "# >>> omnishell:") && strings.HasSuffix(line, ">>>") {
			// Parse section start
			// Format: # >>> omnishell:<id> (v<version>) >>>
			start := strings.Index(line, "omnishell:") + len("omnishell:")
			rest := line[start:]

			// Find the version
			versionStart := strings.Index(rest, "(v")
			versionEnd := strings.Index(rest, ")")
			if versionStart >= 0 && versionEnd > versionStart {
				id := rest[:versionStart-1]
				version := rest[versionStart+2 : versionEnd]
				current = &Section{ID: id, Version: version}
				bodyLines = []string{}
			}
		} else if current != nil && strings.HasPrefix(line, "# <<< omnishell:") && strings.HasSuffix(line, "<<<") {
			// Section end marker
			// Reconstruct body with newlines
			body := strings.Join(bodyLines, "\n")
			if len(bodyLines) > 0 {
				body += "\n"
			}
			current.Body = body
			result = append(result, *current)
			current = nil
			bodyLines = nil
		} else if current != nil {
			// Body line
			bodyLines = append(bodyLines, line)
		}
	}

	return result
}
