package initfile_test

import (
	"strings"
	"testing"
	"time"

	"github.com/JtheGunner/omnishell/internal/initfile"
)

func sections() []initfile.Section {
	return []initfile.Section{
		{ID: "completion", Version: "1.0.0", Body: "autoload -Uz compinit && compinit\n"},
		{ID: "fzf", Version: "1.2.0", Body: "source fzf.zsh\n"},
		{ID: "empty", Version: "1.0.0", Body: ""},
	}
}

func TestBuildStructure(t *testing.T) {
	ts := time.Date(2026, 9, 2, 22, 41, 3, 0, time.UTC)
	got := initfile.Build("zsh", sections(), ts)

	if !strings.Contains(got, "GENERATED BY omnishell") {
		t.Fatal("missing generated header")
	}
	if !strings.Contains(got, "# >>> omnishell:completion (v1.0.0) >>>") ||
		!strings.Contains(got, "# <<< omnishell:completion <<<") {
		t.Fatalf("missing completion markers:\n%s", got)
	}
	if strings.Contains(got, "omnishell:empty") {
		t.Fatal("empty section should be skipped")
	}
	if !strings.Contains(got, "Content hash: "+initfile.ContentHash(sections())) {
		t.Fatal("header hash mismatch")
	}
	if strings.Index(got, "omnishell:completion") > strings.Index(got, "omnishell:fzf") {
		t.Fatal("section order not preserved")
	}
}

func TestDetectHandEdit(t *testing.T) {
	ts := time.Date(2026, 9, 2, 22, 41, 3, 0, time.UTC)
	content := initfile.Build("zsh", sections(), ts)

	edited, err := initfile.DetectHandEdit(content, sections())
	if err != nil {
		t.Fatal(err)
	}
	if edited {
		t.Fatal("freshly built file reported as hand-edited")
	}

	tampered := strings.Replace(content, "autoload -Uz compinit && compinit", "rm -rf /", 1)
	edited, _ = initfile.DetectHandEdit(tampered, sections())
	if !edited {
		t.Fatal("tampered file not detected")
	}

	edited, _ = initfile.DetectHandEdit("no header here", sections())
	if !edited {
		t.Fatal("headerless content should count as edited")
	}
}

func TestContentHashOrderSensitive(t *testing.T) {
	s := sections()
	swapped := []initfile.Section{s[1], s[0], s[2]}
	if initfile.ContentHash(s) == initfile.ContentHash(swapped) {
		t.Fatal("hash should depend on section order")
	}
}
